### ISSUE TITLE
Lambda function fails when no permissionsets provisioned to account

### ISSUE THREAD

**Issue by dennisneuman** [PeterBengtson/AFT-SSO-account-configuration#1]
Hi,

Sorry to bother you but the configure lamba throws this exception:

_[ERROR] KeyError: 'PermissionSets'
Traceback (most recent call last):
  File "/var/task/app.py", line 33, in lambda_handler
    account_permission_sets = get_account_permission_sets(account_id)
  File "/var/task/app.py", line 110, in get_account_permission_sets
    pm_set_arns = response['PermissionSets']_
    
 Looking at the code I suspect that this is because the freshly created accounts don't have any permissionsets provisioned.
 So it receives an empty response not including the PermissionSets key (pm_set_arns = response['PermissionSets']).
 
Is there a reason the code assumes at least one permissionset has been added (manually?) or am I missing something?

Best regards,
Dennis

**Comment by PeterBengtson** [comment]
No bother at all, quite the opposite: thanks for contacting me. This utility does not create permission sets, it provisions existing permission sets to accounts and/or users. Can you give me an example of one of your module definitions and its `custom_fields`?

There are multiple ways of defining permission sets and configuring SSO core configuration. You'll find a utility of mine here: https://github.com/PeterBengtson/AWS-Core-SSO-Configuration.

**Comment by PeterBengtson** [comment]
But then, a new account will always have the default SSO permission sets assigned to it: `AWSSecurityAuditors`, `AWSControlTowerAdmins`, and `AWSSecurityAuditPowerUsers`, if you're using Control Tower. Also, the `boto3` SSO function `list_permission_sets_provisioned_to_account` (described here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/list_permission_sets_provisioned_to_account.html) always returns a response of the following structure:

```
{
    'NextToken': 'string',
    'PermissionSets': [
        'string',
    ]
}
```

The behaviour you're seeing indicates that this is not the case; however, there is nothing in the `boto3` or AWS API documentation that indicates this has changed. I will add an extra check for this specific case, that of the PermissionSets data missing entirely, just in case.

Are you using Control Tower?

**Comment by PeterBengtson** [comment]
I have committed a fix for the case where the AWS API returns a value not conforming to its output specifications. Give it a spin and let me know how it works for you.

**Comment by dennisneuman** [comment]
Ah great thanks, just to clarify. I am using Control Tower but since I use Azure AD as idp so I did not enable SSO group creation by Control Tower. And indeed strangely enough the cli returns an empty response for me so I assume the same happens in the lamba function.

`aws --version
aws-cli/2.11.20 Python/3.11.3 Darwin/22.5.0 exe/x86_64 prompt/off`

**Comment by PeterBengtson** [comment]
It seems we have an undocumented edge case API response, then. I'll contact AWS Support and point out the discrepancy. Then I'll take a look at the rest of the code and introduce similar protection for a few other API calls.

**Comment by dennisneuman** [comment]
I can confirm that after deploying commit f6fa8f4 things work as expected. 
Really appreciate it, thanks!

**Comment by PeterBengtson** [comment]
Brilliant! :)Thanks for contacting me and for helping improve this utility. I'll close the issue for now.
